name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: update submodules 
      run: |
        git submodule update --init --recursive --remote
      shell: cmd
    - name: build
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com" %GITHUB_WORKSPACE%\proxychains.exe.sln /build "Release^|x64"
      shell: cmd
      

